server:
  grpc_port: 9000
  http_port: 8081
  upload_max_size: 1073741824  # 1GB

redis:
  addr: "redis:6379"
  user: ""
  password: ""
  db: 0
  pool_size: 10

storage:
  type: "local"
  local_dir: "./uploads"
  minio:
    endpoint: "minio:9000"
    access_key: "minioadmin"
    secret_key: "minioadmin"
    bucket: "clouddrive"
    use_ssl: false

security:
  jwt_secret: "your-super-secret-key-for-jwt-token-signing" 