database:
  user: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  name: clouddrive
  charset: utf8mb4
  parseTime: true
  loc: Local

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  pool_size: 10 