database:
  user: root
  password: 123456
  host: mysql-test
  port: 3306
  name: clouddrive
  charset: utf8mb4
  parseTime: true
  loc: Local

redis:
  addr: "redis-test:6379"
  user: ""
  password: ""
  db: 0
  pool_size: 10

storage:
  type: local
  local_dir: uploads 
  minio:
    endpoint: "minio-test:9000"
    access_key: "minioadmin"
    secret_key: "minioadmin"
    bucket: "clouddrive"
    use_ssl: false 
  chunk_server:
    enabled: true
    url: "http://chunk.clouddrive.local:30080"
    temp_dir: "/tmp/chunk_client"
    use_service_discovery: true
    public_url: "http://chunk.clouddrive.local:30080"

environment: "development"

# 监控配置
monitoring:
  log_level: "info"
  log_file: "logs/app.log"
  log_max_size: 100  # MB
  log_max_age: 30    # days
  log_max_backups: 10
  log_compress: true
  metrics_enabled: true
  health_check_timeout: 5s 