database:
  user: root
  password: 123456
  host: 127.0.0.1
  port: 32306
  name: clouddrive
  charset: utf8mb4
  parseTime: true
  loc: Local

redis:
  addr: "localhost:32381"
  user: ""
  password: ""
  db: 0
  pool_size: 10

storage:
  type: local
  local_dir: uploads 
  minio:
    endpoint: "localhost:9000"
    access_key: "minioadmin"
    secret_key: "minioadmin"
    bucket: "clouddrive"
    use_ssl: false 
  chunk_server:
    enabled: false
    url: "http://localhost:8081"
    temp_dir: "/tmp/chunk_client" 