basePath: /api
definitions:
  file.File:
    properties:
      hash:
        description: 外键关联 FileContent
        type: string
      id:
        type: string
      name:
        type: string
      owner_id:
        type: integer
      parent_id:
        type: string
      type:
        type: string
      upload_time:
        type: string
    type: object
  file.ListFilesResponse:
    properties:
      files:
        items:
          $ref: '#/definitions/file.File'
        type: array
      total:
        type: integer
    type: object
  file.MoveFileRequest:
    properties:
      new_parent_id:
        type: string
    type: object
  file.RenameFileRequest:
    properties:
      new_name:
        type: string
    type: object
  handler.CreateFolderRequest:
    properties:
      name:
        type: string
      parent_id:
        type: string
    type: object
  handler.PrivateShareRequest:
    properties:
      expire_hours:
        maximum: 168
        minimum: 1
        type: integer
      resource_id:
        type: string
    required:
    - expire_hours
    - resource_id
    type: object
  handler.PrivateShareResponse:
    properties:
      access_code:
        type: string
      expire_at:
        type: integer
      share_link:
        type: string
    type: object
  handler.PublicShareAccessResponse:
    properties:
      expire_at:
        type: integer
      name:
        type: string
      owner_id:
        type: integer
      resource_id:
        type: string
      type:
        type: string
    type: object
  handler.PublicShareRequest:
    properties:
      expire_hours:
        description: 1~168小时
        maximum: 168
        minimum: 1
        type: integer
      resource_id:
        type: string
    required:
    - expire_hours
    - resource_id
    type: object
  handler.PublicShareResponse:
    properties:
      expire_at:
        type: integer
      share_link:
        type: string
    type: object
  user.LoginRequest:
    properties:
      password:
        maxLength: 32
        minLength: 6
        type: string
      username:
        maxLength: 32
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
  user.RegisterRequest:
    properties:
      password:
        maxLength: 32
        minLength: 6
        type: string
      username:
        maxLength: 32
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: 云盘系统后端 API 文档
  title: CloudDrive API
  version: "1.0"
paths:
  /files:
    get:
      consumes:
      - application/json
      description: 获取指定目录下的文件和文件夹，支持分页和排序
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 父目录ID，根目录为0
        in: query
        name: parent_id
        type: string
      - description: 页码，默认1
        in: query
        name: page
        type: integer
      - description: 每页数量，默认10
        in: query
        name: page_size
        type: integer
      - description: 排序字段，默认upload_time
        in: query
        name: order_by
        type: string
      - description: 排序方式，asc/desc，默认desc
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/file.ListFilesResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 获取文件/文件夹列表
      tags:
      - 文件模块
  /files/{id}:
    delete:
      consumes:
      - application/json
      description: 删除指定文件
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文件ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 删除文件
      tags:
      - 文件模块
  /files/{id}/move:
    put:
      consumes:
      - application/json
      description: 移动指定文件/文件夹到新目录
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文件ID
        in: path
        name: id
        required: true
        type: string
      - description: 新父目录ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/file.MoveFileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 移动文件/文件夹
      tags:
      - 文件模块
  /files/{id}/rename:
    put:
      consumes:
      - application/json
      description: 重命名指定文件
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文件ID
        in: path
        name: id
        required: true
        type: string
      - description: 新文件名
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/file.RenameFileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 重命名文件
      tags:
      - 文件模块
  /files/download/{id}:
    get:
      consumes:
      - application/json
      description: 下载指定文件
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文件ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 下载文件
      tags:
      - 文件模块
  /files/preview/{id}:
    get:
      consumes:
      - application/json
      description: 在线预览指定文件，仅支持已登录用户
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文件ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 文件在线预览
      tags:
      - 文件模块
  /files/search:
    get:
      consumes:
      - application/json
      description: 按文件名模糊搜索文件
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文件名
        in: query
        name: name
        required: true
        type: string
      - description: 页码，默认1
        in: query
        name: page
        type: integer
      - description: 每页数量，默认10
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/file.ListFilesResponse'
      summary: 搜索文件
      tags:
      - 文件模块
  /files/upload:
    post:
      consumes:
      - multipart/form-data
      description: 上传文件到指定目录
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      - description: 父目录ID，根目录为0
        in: formData
        name: parent_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 上传文件
      tags:
      - 文件模块
  /folders:
    post:
      consumes:
      - application/json
      description: 在指定目录下新建文件夹
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文件夹信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handler.CreateFolderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 新建文件夹
      tags:
      - 文件模块
  /share:
    delete:
      consumes:
      - application/json
      description: 取消指定的分享链接（token或resource_id），仅分享创建者可操作
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 分享Token
        in: path
        name: token
        type: string
      - description: 资源ID
        in: query
        name: resource_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: 取消分享
      tags:
      - 分享
  /share/{token}:
    get:
      consumes:
      - application/json
      description: 访问公开或私有分享链接，私有需access_code
      parameters:
      - description: 分享Token
        in: path
        name: token
        required: true
        type: string
      - description: 访问码(私有分享)
        in: query
        name: access_code
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.PublicShareAccessResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "410":
          description: Gone
          schema:
            additionalProperties: true
            type: object
      summary: 访问分享链接
      tags:
      - 分享
  /share/download/{token}:
    get:
      consumes:
      - application/json
      description: 通过分享链接下载文件，私有需access_code
      parameters:
      - description: 分享Token
        in: path
        name: token
        required: true
        type: string
      - description: 访问码(私有分享)
        in: query
        name: access_code
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "410":
          description: Gone
          schema:
            additionalProperties: true
            type: object
      summary: 分享文件下载
      tags:
      - 分享
  /share/private:
    get:
      consumes:
      - application/json
      description: 查询指定文件的未过期私有分享链接
      parameters:
      - description: 资源ID
        in: query
        name: resource_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.PrivateShareResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: 查询已有未过期的私有分享
      tags:
      - 分享
    post:
      consumes:
      - application/json
      description: 创建一个私有分享链接，需访问码访问
      parameters:
      - description: 私有分享参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handler.PrivateShareRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.PrivateShareResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: 创建私有分享链接
      tags:
      - 分享
  /share/public:
    get:
      consumes:
      - application/json
      description: 查询指定文件的未过期公开分享链接
      parameters:
      - description: 资源ID
        in: query
        name: resource_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.PublicShareResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: 查询已有未过期的公开分享
      tags:
      - 分享
    post:
      consumes:
      - application/json
      description: 创建一个公开分享链接，任何人可访问
      parameters:
      - description: 公开分享参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handler.PublicShareRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.PublicShareResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: 创建公开分享链接
      tags:
      - 分享
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 登录参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: 用户登录
      tags:
      - 用户模块
  /user/register:
    post:
      consumes:
      - application/json
      description: 注册新用户
      parameters:
      - description: 注册参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: 用户注册
      tags:
      - 用户模块
swagger: "2.0"
