basePath: /api
definitions:
  file.File:
    properties:
      hash:
        description: 外键关联 FileContent
        type: string
      id:
        type: string
      name:
        type: string
      owner_id:
        type: integer
      parent_id:
        type: string
      type:
        type: string
      upload_time:
        type: string
    type: object
  file.ListFilesResponse:
    properties:
      files:
        items:
          $ref: '#/definitions/file.File'
        type: array
      total:
        type: integer
    type: object
  file.MoveFileRequest:
    properties:
      new_parent_id:
        type: string
    type: object
  file.RenameFileRequest:
    properties:
      new_name:
        type: string
    type: object
  user.LoginRequest:
    properties:
      password:
        maxLength: 32
        minLength: 6
        type: string
      username:
        maxLength: 32
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
  user.RegisterRequest:
    properties:
      password:
        maxLength: 32
        minLength: 6
        type: string
      username:
        maxLength: 32
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: 云盘系统后端 API 文档
  title: CloudDrive API
  version: "1.0"
paths:
  /files:
    get:
      consumes:
      - application/json
      description: 获取指定目录下的文件和文件夹，支持分页和排序
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 父目录ID，根目录为0
        in: query
        name: parent_id
        type: string
      - description: 页码，默认1
        in: query
        name: page
        type: integer
      - description: 每页数量，默认10
        in: query
        name: page_size
        type: integer
      - description: 排序字段，默认upload_time
        in: query
        name: order_by
        type: string
      - description: 排序方式，asc/desc，默认desc
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/file.ListFilesResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 获取文件/文件夹列表
      tags:
      - 文件模块
  /files/{id}:
    delete:
      consumes:
      - application/json
      description: 删除指定文件
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文件ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 删除文件
      tags:
      - 文件模块
  /files/{id}/move:
    put:
      consumes:
      - application/json
      description: 移动指定文件/文件夹到新目录
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文件ID
        in: path
        name: id
        required: true
        type: string
      - description: 新父目录ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/file.MoveFileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 移动文件/文件夹
      tags:
      - 文件模块
  /files/{id}/rename:
    put:
      consumes:
      - application/json
      description: 重命名指定文件
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文件ID
        in: path
        name: id
        required: true
        type: string
      - description: 新文件名
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/file.RenameFileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 重命名文件
      tags:
      - 文件模块
  /files/download/{id}:
    get:
      consumes:
      - application/json
      description: 下载指定文件
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文件ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 下载文件
      tags:
      - 文件模块
  /files/upload:
    post:
      consumes:
      - multipart/form-data
      description: 上传文件到指定目录
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      - description: 父目录ID，根目录为0
        in: formData
        name: parent_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 上传文件
      tags:
      - 文件模块
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 登录参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: 用户登录
      tags:
      - 用户模块
  /user/register:
    post:
      consumes:
      - application/json
      description: 注册新用户
      parameters:
      - description: 注册参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: 用户注册
      tags:
      - 用户模块
swagger: "2.0"
